Repository entando-k8s/environment-entando-jx-dev, pull requests merged in 2020-02, with the labels that each got.

#17 chore(deps): bump https://github.com/entando-k8s/app-builder.git
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  repositories/templates/entando-k8s-app-builder-sr.yaml
Labels: size/S, updatebot

#18 chore(deps): bump https://github.com/entando-k8s/entando-jx-nodejs11.git
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  repositories/templates/entando-k8s-entando-jx-nodejs11-sr.yaml
Labels: size/S, updatebot

#19 Added entando builder podTemplate configmaps
  fix-config.sh
  jenkins-x-pod-template-entando-jx-maven-java11.yaml
  jenkins-x-pod-template-entando-jx-nodejs11.yaml
Labels: approved, size/L

#20 chore(deps): bump https://github.com/entando-k8s/entando-k8s-dbjob.git
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  repositories/templates/entando-k8s-entando-k8s-dbjob-sr.yaml
Labels: size/S, updatebot

#21 chore(deps): bump
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  repositories/templates/entando-entando-keycloak-sr.yaml
Labels: size/S, updatebot

#22 chore(deps): bump https://github.com/entando-k8s/entando-jx-nodejs12.git
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  repositories/templates/entando-k8s-entando-jx-nodejs12-sr.yaml
Labels: approved, size/S, updatebot
