Repository entando-k8s/environment-entando-jx-dev, pull requests merged in 2020-01, with the labels that each got.

#1 chore(deps): bump https://github.com/entando-k8s-infrastructure/entando-jx-maven-java11.git
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  repositories/templates/entando-k8s-infrastructure-entando-jx-maven-java11-sr.yaml
Labels: size/M, updatebot

#2 chore(deps): bump https://github.com/entando-k8s-infrastructure/entando-k8s-infrastructure-parent.git
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  repositories/templates/entando-k8s-infrastructure-entando-k8s-infrastructure-parent-sr.yaml
Labels: size/S, updatebot

#3 chore(deps): bump
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  repositories/templates/entando-k8s-infrastructure-entando-jx-maven-java11-sr.yaml
  repositories/templates/entando-k8s-infrastructure-entando-k8s-custom-model-sr.yaml
Labels: size/M, updatebot

#4 chore(deps): bump https://github.com/entando-k8s-infrastructure/entando-k8s-operator-common.git
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  repositories/templates/entando-k8s-infrastructure-entando-k8s-operator-common-sr.yaml
Labels: size/S, updatebot

#5 chore(deps): bump https://github.com/entando-k8s-infrastructure/entando-k8s-keycloak-controller.git
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  repositories/templates/entando-k8s-infrastructure-entando-k8s-keycloak-controller-sr.yaml
Labels: size/S, updatebot

#8 chore(deps): bump
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  repositories/templates/entando-k8s-entando-k8s-app-controller-sr.yaml
  repositories/templates/entando-k8s-entando-k8s-plugin-controller-sr.yaml
Labels: size/M, updatebot

#9 chore(deps): bump https://github.com/entando-k8s/entando-k8s-app-plugin-link-controller.git
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  repositories/templates/entando-k8s-entando-k8s-app-plugin-link-controller-sr.yaml
Labels: size/S, updatebot

#10 chore(deps): bump https://github.com/entando-k8s/entando-k8s-composite-app-controller.git
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  repositories/templates/entando-k8s-entando-k8s-composite-app-controller-sr.yaml
Labels: size/S, updatebot

#11 chore(deps): bump https://github.com/entando-k8s/entando-k8s-controller-coordinator.git
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  repositories/templates/entando-k8s-entando-k8s-controller-coordinator-sr.yaml
Labels: size/S, updatebot

#12 Plank integration
  jenkins-x.yml
Labels: approved, size/XS

#13 chore(deps): bump https://github.com/entando-k8s/entando-component-manager.git
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  repositories/templates/entando-k8s-entando-component-manager-sr.yaml
Labels: size/S, updatebot

#14 chore(deps): bump https://github.com/entando-k8s/web-commons.git
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  repositories/templates/entando-k8s-web-commons-sr.yaml
Labels: size/S, updatebot

#15 Add jx-app-ui 0.1.36
  env/jx-app-ui/README.MD
  env/jx-app-ui/templates/app.yaml
  env/jx-app-ui/values.yaml
  env/requirements.yaml
Labels: size/M

#16 chore(deps): bump https://github.com/entando-k8s/entando-de-app.git
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  repositories/templates/entando-k8s-entando-de-app-sr.yaml
Labels: size/S, updatebot
